import { execa } from 'execa';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { basename, dirname, join } from 'node:path';

export const DIRECTORY_CHANGE_COMMANDS = ['switch', 'clone', 'pr'] as const;
export const SHELL_NAMES = ['bash', 'zsh', 'fish', 'nu'] as const;

export type ShellName = 'bash' | 'zsh' | 'fish' | 'nu';

const GW_RC_BLOCK_START = '# >>> gw >>>';
const GW_RC_BLOCK_END = '# <<< gw <<<';
const BASH_RC_CANDIDATES = ['.bashrc', '.bash_profile', '.profile'] as const;

const BASH_LIKE_SHELLS = new Set<ShellName>(['bash', 'zsh']);

export interface ShellIntegrationInstallResult {
  shell: ShellName;
  rcFilePath: string;
  rcFileLabel: string;
  initFilePath: string;
  updatedRcFile: boolean;
}

function normalizeShellName(value: string | undefined): ShellName | null {
  if (!value) {
    return null;
  }

  const shellName = basename(value).replace(/^-+/u, '').toLowerCase();
  if ((SHELL_NAMES as readonly string[]).includes(shellName)) {
    return shellName as ShellName;
  }

  return null;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function getConfigRoot(): string {
  return process.env.XDG_CONFIG_HOME || join(homedir(), '.config');
}

function getGwConfigDir(): string {
  return join(getConfigRoot(), 'gw');
}

function getShellInitFilePath(shell: ShellName): string {
  return join(getGwConfigDir(), `init.${shell}`);
}

function getFishFunctionFilePath(): string {
  return join(getConfigRoot(), 'fish', 'functions', 'gw.fish');
}

async function detectParentShellName(): Promise<ShellName | null> {
  try {
    const result = await execa('ps', [
      '-p',
      String(process.ppid),
      '-o',
      'comm=',
    ]);
    return normalizeShellName(result.stdout.trim());
  } catch {
    return null;
  }
}

async function getBashRcFilePath(): Promise<string> {
  const homeDir = homedir();

  for (const candidate of BASH_RC_CANDIDATES) {
    const candidatePath = join(homeDir, candidate);
    if (await pathExists(candidatePath)) {
      return candidatePath;
    }
  }

  return join(homeDir, '.bashrc');
}

export async function detectShellName(): Promise<ShellName | null> {
  const parentShellName = await detectParentShellName();
  if (parentShellName) {
    return parentShellName;
  }

  return normalizeShellName(process.env.SHELL);
}

export async function resolveShellName(shell?: string): Promise<ShellName> {
  if (shell) {
    const normalizedShellName = normalizeShellName(shell);
    if (!normalizedShellName) {
      throw new Error(`unsupported shell: ${shell}`);
    }

    return normalizedShellName;
  }

  const detectedShellName = await detectShellName();
  if (!detectedShellName) {
    throw new Error(
      'could not detect your shell; rerun with an explicit shell name'
    );
  }

  return detectedShellName;
}

export async function getShellRcFilePath(shell: ShellName): Promise<string> {
  const homeDir = homedir();
  const configRoot = getConfigRoot();

  switch (shell) {
    case 'bash':
      return getBashRcFilePath();
    case 'zsh':
      return join(homeDir, '.zshrc');
    case 'fish':
      return join(configRoot, 'fish', 'config.fish');
    case 'nu':
      return join(configRoot, 'nushell', 'config.nu');
  }
}

export async function getShellInstallPath(shell: ShellName): Promise<string> {
  if (shell === 'fish') {
    return getFishFunctionFilePath();
  }

  return getShellRcFilePath(shell);
}

function escapeDoubleQuotedString(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('"', '\\"');
}

function renderRcSourceLine(shell: ShellName, initFilePath: string): string {
  const quotedInitFilePath = `"${escapeDoubleQuotedString(initFilePath)}"`;

  switch (shell) {
    case 'bash':
    case 'zsh':
      return `[ -f ${quotedInitFilePath} ] && source ${quotedInitFilePath}`;
    case 'fish':
      return `test -f ${quotedInitFilePath}; and source ${quotedInitFilePath}`;
    case 'nu':
      return `source ${quotedInitFilePath}`;
  }
}

function renderRcBlock(shell: ShellName, initFilePath: string): string {
  return [
    GW_RC_BLOCK_START,
    '# Generated by gw setup',
    renderRcSourceLine(shell, initFilePath),
    GW_RC_BLOCK_END,
    '',
  ].join('\n');
}

function upsertRcBlock(
  existingText: string,
  block: string
): { text: string; updated: boolean } {
  const blockPattern = new RegExp(
    `${GW_RC_BLOCK_START.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}[\\s\\S]*?${GW_RC_BLOCK_END.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}\\n?`,
    'u'
  );

  if (blockPattern.test(existingText)) {
    const updatedText = existingText.replace(blockPattern, block);
    return {
      text: updatedText,
      updated: updatedText !== existingText,
    };
  }

  const separator =
    existingText === '' || existingText.endsWith('\n') ? '' : '\n';
  return {
    text: `${existingText}${separator}${block}`,
    updated: true,
  };
}

async function readTextFile(path: string): Promise<string> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (
      error &&
      typeof error === 'object' &&
      'code' in error &&
      error.code === 'ENOENT'
    ) {
      return '';
    }

    throw error;
  }
}

export async function installShellIntegration(
  shell: ShellName
): Promise<ShellIntegrationInstallResult> {
  const initFilePath =
    shell === 'fish' ? getFishFunctionFilePath() : getShellInitFilePath(shell);
  const rcFilePath = await getShellRcFilePath(shell);

  if (shell === 'fish') {
    const initText = renderShellInit(shell);
    const existingInitText = await readTextFile(initFilePath);
    const updated = existingInitText !== initText;

    if (updated) {
      await mkdir(dirname(initFilePath), { recursive: true });
      await writeFile(initFilePath, initText, 'utf8');
    }

    return {
      shell,
      rcFilePath: initFilePath,
      rcFileLabel: 'function file',
      initFilePath,
      updatedRcFile: updated,
    };
  }

  await mkdir(dirname(initFilePath), { recursive: true });
  await writeFile(initFilePath, renderShellInit(shell), 'utf8');

  const existingRcText = await readTextFile(rcFilePath);
  const rcBlock = renderRcBlock(shell, initFilePath);
  const { text: updatedRcText, updated } = upsertRcBlock(
    existingRcText,
    rcBlock
  );

  if (updated) {
    await mkdir(dirname(rcFilePath), { recursive: true });
    await writeFile(rcFilePath, updatedRcText, 'utf8');
  }

  return {
    shell,
    rcFilePath,
    rcFileLabel: 'rc file',
    initFilePath,
    updatedRcFile: updated,
  };
}

export function getSessionActivationCommand(shell: ShellName): string {
  switch (shell) {
    case 'bash':
    case 'zsh':
      return 'eval "$(gw shell-init)"';
    case 'fish':
      return 'gw shell-init | source';
    case 'nu':
      return 'let _gw_init = ($nu.default-config-dir | path join "gw-init.nu"); gw shell-init | save --force $_gw_init; source $_gw_init';
  }
}

function renderBashLikeShellInit(): string {
  return `__gw_needs_cd() {
  case "$1" in
    switch|clone|pr) return 0 ;;
    *) return 1 ;;
  esac
}

__gw_needs_source() {
  case "$1" in
    setup) return 0 ;;
    *) return 1 ;;
  esac
}

gw() {
  if [[ $# -gt 0 ]] && __gw_needs_cd "$1"; then
    local _gw_tmpfile
    _gw_tmpfile="$(mktemp "\${TMPDIR:-/tmp}/gw.XXXXXX")" || return 1

    GW_CWD_FILE="$_gw_tmpfile" command gw "$@"
    local _gw_status=$?

    if [[ $_gw_status -eq 0 && -s "$_gw_tmpfile" ]]; then
      local _gw_target
      IFS= read -r _gw_target < "$_gw_tmpfile"
      if [[ -n "$_gw_target" ]]; then
        builtin cd "$_gw_target" || _gw_status=$?
      fi
    fi

    rm -f "$_gw_tmpfile"
    return $_gw_status
  fi

  if [[ $# -gt 0 ]] && __gw_needs_source "$1"; then
    local _gw_tmpfile
    _gw_tmpfile="$(mktemp "\${TMPDIR:-/tmp}/gw.XXXXXX")" || return 1

    GW_SOURCE_FILE="$_gw_tmpfile" command gw "$@"
    local _gw_status=$?

    if [[ $_gw_status -eq 0 && -s "$_gw_tmpfile" ]]; then
      local _gw_source
      IFS= read -r _gw_source < "$_gw_tmpfile"
      if [[ -n "$_gw_source" && -f "$_gw_source" ]]; then
        source "$_gw_source" || _gw_status=$?
      fi
    fi

    rm -f "$_gw_tmpfile"
    return $_gw_status
  fi

  command gw "$@"
}
`;
}

function renderFishShellInit(): string {
  return `function __gw_needs_cd
    switch $argv[1]
        case switch clone pr
            return 0
        case '*'
            return 1
    end
end

function __gw_needs_source
    switch $argv[1]
        case setup
            return 0
        case '*'
            return 1
    end
end

function gw
    if test (count $argv) -gt 0; and __gw_needs_cd $argv[1]
        set -l tmpdir /tmp
        if set -q TMPDIR
            set tmpdir $TMPDIR
        end

        set -l tmpfile (mktemp "$tmpdir/gw.XXXXXX")
        or return 1

        env GW_CWD_FILE="$tmpfile" command gw $argv
        set -l _gw_status $status

        if test $_gw_status -eq 0; and test -s "$tmpfile"
            set -l target (string trim -- (command cat -- "$tmpfile"))
            if test -n "$target"
                cd "$target"
                or set _gw_status $status
            end
        end

        command rm -f -- "$tmpfile"
        return $_gw_status
    end

    if test (count $argv) -gt 0; and __gw_needs_source $argv[1]
        set -l tmpdir /tmp
        if set -q TMPDIR
            set tmpdir $TMPDIR
        end

        set -l tmpfile (mktemp "$tmpdir/gw.XXXXXX")
        or return 1

        env GW_SOURCE_FILE="$tmpfile" command gw $argv
        set -l _gw_status $status

        if test $_gw_status -eq 0; and test -s "$tmpfile"
            set -l source_path (string trim -- (command cat -- "$tmpfile"))
            if test -n "$source_path"; and test -f "$source_path"
                source "$source_path"
                or set _gw_status $status
            end
        end

        command rm -f -- "$tmpfile"
        return $_gw_status
    end

    command gw $argv
end
`;
}

function renderNuShellInit(): string {
  return `def __gw_needs_cd [cmd: string] {
  $cmd in ['switch', 'clone', 'pr']
}

def __gw_needs_source [cmd: string] {
  $cmd == 'setup'
}

def --env gw [...args] {
  if (($args | length) == 0) {
    ^gw
    return
  }

  let cmd = ($args | first)

  if not (__gw_needs_cd $cmd) and not (__gw_needs_source $cmd) {
    ^gw ...$args
    return
  }

  let tmpdir = ($env.TMPDIR? | default '/tmp')
  let tmpfile = (^mktemp $"($tmpdir)/gw.XXXXXX" | str trim)

  let handoff_env = if (__gw_needs_cd $cmd) {
    { GW_CWD_FILE: $tmpfile }
  } else {
    { GW_SOURCE_FILE: $tmpfile }
  }

  with-env $handoff_env {
    ^gw ...$args
  }

  let status = ($env.LAST_EXIT_CODE? | default 0)

  if ($status == 0) and (__gw_needs_cd $cmd) and ($tmpfile | path exists) {
    let target = (open --raw $tmpfile | str trim)
    if $target != '' {
      cd $target
    }
  }

  if ($status == 0) and (__gw_needs_source $cmd) and ($tmpfile | path exists) {
    let source_file = (open --raw $tmpfile | str trim)
    if ($source_file != '') and ($source_file | path exists) {
      source $source_file
    }
  }

  ^rm -f $tmpfile
  load-env { LAST_EXIT_CODE: $status }
}
`;
}

export function renderShellInit(shell: ShellName): string {
  if (BASH_LIKE_SHELLS.has(shell)) {
    return renderBashLikeShellInit();
  }

  if (shell === 'fish') {
    return renderFishShellInit();
  }

  return renderNuShellInit();
}
